default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password:

development:
  <<: *default
  database: huhaiyang

test:
  <<: *default
  database: huhaiyang_test

production:
  <<: *default
  database: huhaiyang
